#+title: A Bite Of Cybersecurity
#+OPTIONS: author:"Luo Jie" ^:{}
#+HUGO_BASE_DIR: ./../
#+HUGO_SECTION: posts
#+HUGO_CUSTOM_FRONT_MATTER: :toc true :isCJKLanguage true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2023-05-06]
#+HUGO_TAGS:
#+HUGO_CATEGORIES:
#+hugo_weight: auto
#+hugo_auto_set_lastmod: t
#+startup: noindent
* Terms :@terms:

All posts in here will have the category set to /terms/.
** 工行融 e 行个人信息保护政策分析 :org:hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: PII-Analysis-for-ICBC
:EXPORT_AUTHOR: 丛朝
:EXPORT_DATE: [2023-05-29 Sun]
:END:

#+begin_quote
本文尝试对工行融 e 行的个人信息保护政策做出一些分析，我尝试通过这些分析得出一些关键字。以作为其他分析时的参考。
#+end_quote

*** 基于功能的数据和基于数据的功能
从信息安全三位一体的角度上说，我们需要保护的一是服务，二是数据，即 Service & Data。在做个人信息识别，和资产识别时，可以分别从基于功能的数据和基于数据的功能的角度来展开。

打比方，在穷举一个产品具有的所有功能的同时，我们可以将每一个功能用到的数据，特别是个人信息相关的数据整理出来。如此，在产品功能逻辑上，就可以达到全部的覆盖。

从我个人的角度，“基于功能的数据”恐怕是更为适合我自己去识别个人信息以及资产的方式。

那如何理解“基于数据的功能”呢？在一个系统的运行环境中，个人（actor）这是比较容易识别的，而有关个人的数据，在每个评估者那儿都应该有其积累的经验值。根据这个经验值，评估者在运行环境中，可去结合已有的功能分析，更进一步，可以去评估将来可能会有的功能场景。

从实践的角度来看，我认为评估者应当先对系统运行环境进行全方位分析，基于分析结果，评估个人信息及资产。然后再用自己的经验值作为验证。
所以说，基于功能的数据和基于数据的功能，两者在行程安全概念的过程中，相辅相成，缺一不可。

*** 工行融 e 行关键字识别
为了找出这些关键字，我对原文中加粗的字体，做了解析。同时也尝试做了一个词云。执行的代码如下：
#+begin_src python :session :results file
import sys
import matplotlib
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from wordcloud import STOPWORDS
from requests_html import HTMLSession

# get links
session = HTMLSession()
url = 'https://m.icbc.com.cn/ICBC/disclaimer/2.htm'
r = session.get(url)

# select the selector
sel = '#infoDetailPage > div.infoText.fs16 > p > strong'
bold_text = r.html.find(sel)

def get_text_from_sel(sel):
    mylist = []
    try:
        results = sel
        for result in results:
            mytext = result.text
            mylist.append(mytext)
        return mylist
    except:
        return None

bold_text_string = ' '.join(get_text_from_sel(bold_text))

# set STOPWORDS
sw = set(STOPWORDS)
sw.add("一")
sw.add("二")
sw.add("三")

wordcloud = WordCloud(scale=4,
                      background_color='white',
                      stopwords=sw,
                      font_path='/usr/share/fonts/OTF/NotoSansCJKsc-Regular.otf').generate(bold_text_string)

# plt, fontset, imshow, etc
from matplotlib import font_manager
font_dirs = '/home/lj/Downloads/transfonter.org-unpack-20230527-152629'
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)

# %matplotlib inline
plt.figure(dpi=300, figsize=(24,8))
matplotlib.rcParams['font.family'] = 'WenQuanYi Zen Hei'
plt.title(label='常见水果热力图')
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
# plt.show()
fname = '/home/lj/Pictures/icbc_pii_bold_text.png'
plt.savefig(fname)
fname
#+end_src

** 工行融 e 行个人信息保护政策 :org:hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: A-PII-Example-from-ICBC
:EXPORT_AUTHOR: 丛朝
:EXPORT_DATE:
:END:
[2023-05-15 Mon 12:15]

#+begin_quote
本文对原文做了个别修改，如需参考原文，见：https://m.icbc.com.cn/ICBC/disclaimer/2.htm
#+end_quote
我是工商银行的用户，前几天在使用该银行服务的时候，在手机端被提示了工商银行最新的个人信息保护政策。记录以下要点。

 * 问：工行融 e 行将对个人信息做哪些处理？ :: 收集、使用、存储、提供、转让、公开和删除


数据使用实体需要向数据被收集个体（简称“个体”）阐述相关事宜，见下：
 * 数据使用实体将说明个体信息类型及其用途，以便数据个体了解针对某一特定功能收集个人信息的目的、方式、范围及可能的后果等。
 * 当个体使用某些功能时，数据使用实体需获得个体的明示同意后，可收集个体的某些敏感个人信息，例如个体的 *通讯录*, *生物识别信息* 等，拒绝提供这些信息会影响个体正常使用相关功能。
 * 数据使用实体不应主动提供或转让个体的个人信息与第三方，如存在其他提供或转让个体个人信息情形，数据使用实体需征得个体的明示同意。


  * 问：什么是明示同意？ :: explicit consent 明示同意是指个体通过书面、口头等方式主动作出纸质或电子形式的声明，或者自主作出肯定性动作，对个体的个人信息进行特定处理作出明确授权的行为。
  * 问：肯定性动作包括哪些？ :: 肯定性动作包括个体的主动勾选、主动点击“确定”“同意”“注册”“发送”“拨打”、主动填写或提供等。

*** 保护个人信息的几个原则
    [2023-05-17 Wed 10:46]

数据使用实体需要深知个人信息对个体的重要性，需尽力保护个体的个人信息安全。同时，数据使用实体需要恪守以下 7 个原则以保护个体的个人信息：
 * 权责一致原则 :: 指在一个组织中的管理者所拥有的权力应当与所承担的责任相适应的准则。The principle of consistency of rights and responsibilities
 * 目的明确原则 :: 具有合法、正当、必要、明确的个人信息处理目的。
 * 选择同意原则 :: 指向个人信息主体明示个人信息处理目的、方式、范围、规则等，征求其授权同意。换言之，选择同意原则即是要求企业尊重用户的事先同意权，征求同意的行为需发生在未对用户个人信息采取任何措施之前，例如在注册 App 前需勾选同意用户协议等。
 * 最小必要原则 :: Minimum and necessary
 * 确保安全原则 :: 具备与所面临的安全风险相匹配的安全能力、并采取足够的管理措施和技术手段，保护个人信息的保密性、完整性、可用性。
 * 主体参与原则 :: 指向个人信息主体提供能够访问、更正、删除其个人信息，以及撤回同意、注销账户等方法。主体参与原则赋予用户的是事后监督权，保护的是用户事后的反悔权，或者是用户不同意的自由。根据实践，相较于选择同意权，企业更容易忽视用户的主体参与权利。
 * 公开透明原则 :: 以明确、易懂和合理的方式公开处理个人信息的范围、目的、规则等，并接受外部监督


**** 从目的明确原则展开的目的限制原则 (the principle of purpose limitation)[fn:1]
[2023-05-17 Wed 11:26]

目的限制原则 (the principle of purpose limitation), 也称目的拘束原则，是个人信息保护法中最基本的一项原则，贯穿于个人信息处理活动的全过程，无论处理者是谁，也不管属于何种类型的处理活动，都必须受到该原则的拘束。目的限制原则是个人信息保护的基石，在个人信息保护法中具有重要的地位，该原则也被称为个人信息保护法的“帝王条款”。

个人信息保护法第六条规定：
#+begin_quote
处理个人信息应当具有明确、合理的目的，并应当与处理目的直接相关，采取对个人权益影响最小的方式。收集个人信息，应当限于实现处理目的的最小范围，不得过度收集个人信息。
#+end_quote

**** 个人信息，敏感个人信息的定义
[2023-05-17 Wed 12:59]

个人信息是以电子或者其他方式记录的与已识别或者可识别的自然人有关的各种信息，不包括匿名化处理后的信息。
敏感个人信息是一旦泄露或者非法使用，容易导致自然人的个人尊严受到侵害或者人身、财产安全受到危害的个人信息，包括生物识别、宗教信仰、特定身份、医疗健康、金融账户、行踪轨迹等信息，以及不满十四周岁未成年人的个人信息。

*** 工商银行相关的技术细节，索引
[2023-05-22 Mon 12:44]
 * 如何收集和使用个人信息
 * 如何使用 Cookie 技术
 * 如何存储和保护个人信息
 * 如何提供，转让和公开披露个人信息
 * 个体如何管理自身的个人信息
 * 如何处理未成年人信息
 * 政策如何更新
 * 如何联系个人数据使用实体


**** 如何收集和使用个人信息

应用会收集在使用服务过程中主动输入或因使用服务而产生的信息。依据法律法规及监管要求，个体需提供或授权数据使用实体收集必要的个人信息。如果个体拒绝提供，其将无法使用相应功能或服务。

在注册时，按照使用本行、他行发行卡注册的途径，收集的信息略有区别。当使用本行卡注册时，需要：
 * 手机号码
 * 身份证信息
 * 银行卡号
 * =验证银行卡密码=


若使用的是他行发行卡，则需要：
 * 他行卡号
 * 姓名
 * 性别
 * 手机号码
 * 证件类型
 * 证件号码
 * 证件有效期
 * 联络地址
 * 职业
 * 国籍，
同时，将以下信息发送至中国银联或人民银行进行信息查询与核验，以完成注册：
 * 姓名
 * 证件类型
 * 证件号码
 * 他行卡号


 当注册服务时，数据使用实体会采集个体的人脸信息进行身份认证，可能会将人脸信息发送至公安部进行核验并接受验证结果。如果拒绝采集人脸信息，将无法注册该服务。

 当使用数据使用实体提供的服务时，个体可能需要向实体提供或授权实体收集相应服务所需的个人信息。如果个体拒绝提供，个人将无法使用相应功能或服务。

** What is Back Office? :hugo:org:
:PROPERTIES:
:EXPORT_FILE_NAME: What-is-Back-Office
:EXPORT_DATE:
:END:

*** Definition
#+begin_quote
The back office is a counter concept against front office.
#+end_quote

** What is Information Security Management :hugo:org:
:PROPERTIES:
:EXPORT_FILE_NAME: What-is-Information-Security-Management
:EXPORT_DATE: [2023-05-14 Sun]
:END:

#+begin_quote
Information security management validates that appropriate policies, procedures, standards, and guidelines are implemented to ensure business operations are conducted within an acceptable level of risk.
#+end_quote


* Emacs :@emacs:
** doomemacs GUI 中文显示及输入法设置 :hugo:emacs:org:
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_FILE_NAME: doomemacs GUI 中文显示设置
:EXPORT_DATE: [2023-10-03 Mon]
:END:
本文尝试对 doomemacs 的中文字体显示及输入法设置，做一个记录。先说我的配置：
 * 中文显示字体，[[https://github.com/be5invis/Sarasa-Gothic][Sarasa Gothic SC]]
 * 中文输入法，[[https://github.com/tumashu/pyim][PYIM]] + [[https://github.com/merrickluo/liberime][liberime]]
 * 输入法方案，[[https://www.fkxxyz.com/d/cloverpinyin/][四叶草]]
 * 其他…

*** doomemacs GUI frame 中文显示
我一般只会使用窗口模式下的 emacs，此前在使用我自身做的 emacs 配置时，发现配置中文只要简单地设置 CJK 字符就可以，但到了用 doomemacs 时，我尝试了各种方法，总是不行。[[https://emacs-china.org/t/doom-emacs/23513/10][最终发现了一个 hook 的使用]]，如下：
#+begin_src emacs-lisp
(defun +set-cjk()
  "set cjk for Emacs"
  (interactive)
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font)
                      charset
                      (font-spec :family "Sarasa Gothic SC"))))

(add-hook 'after-setting-font-hook #'+set-cjk)
#+end_src
即在 doomemacs 设置完字体以后，我们再来覆盖 CJK 的字体。

*** 中文输入法，PYIM 和 liberime
在 emacs 下，PYIM, emacs-rime, [[https://github.com/laishulu/emacs-smart-input-source][SIS]]，我都用过，我在这里不赘述几种输入法的优劣。单从我个 人的使用习惯来说，我更喜欢 PYIM + liberime 的组合，就像 PYIM 作者说的那样，PYIM 就像我的朋友一样，一直陪伴的着我，而我唯一觉得用得不舒服的地方，在于 PYIM 自带字库，以及云输入法，我总觉得会有些延迟。

基于以上的考虑，最终我想用 PYIM 作为前端，rime 输入法引擎作为后端。至少试下来，整体的效果还是很好的。

*** Rime 输入法方案——四叶草
我喜欢这个输入法方案。我的个人电脑上，安装的是 Arco Linux, 有些字体的支持，emoji 的支持有限，这里着重说下几个问题。

**** 问题一，输入法 emoji 不显示
安装 fontconfig 的配置，见 https://github.com/szclsya/dotfiles/blob/master/fontconfig/fonts.conf

**** 问题二，四叶草输入方案
最好不要和系统输入法共用一个。


* 碎碎念 :cliche:
** 一枝花
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_FILE_NAME: 一枝花
:EXPORT_DATE: [2023-11-21]
:END:
我犹豫了很久，要不要在这个 blog 里写一些稍微偏私人的东西。考虑的点不外乎那么几点，一方面我想找个地方，一个能被人看到，听到的地方说些什么，另一方面，我又不想让知道我有这么一面。我通过一段时间的观察，似乎我周围，没什么人还保留着看 blog 的习惯。

所以我还是在这里写写吧。写什么都好，谁来看都行，我只管写我的。

“一枝花”是彭羚一张专辑的名字，我下班之后从坐班车起，到打开家门。差不多可以将这张专辑从头到尾听两遍。我最早听彭羚的歌，是在十二年前一次晚间下班，那时加班班车，司机师傅喜欢放一个音乐电台，歌曲以怀旧为主。我听了王杰，张清芳，齐秦这些人的歌，张清芳也是很特别的歌手，我听了她的《加州阳光》，《大雨的夜里》，《对话练习》等等，也陪我度过了很多孤独的时光。但这次下班是特别的，我打着瞌睡，电台里放的是彭羚的《给我一段仁爱路》，这首歌前奏乍听很聒噪，歌词也很无脑。等到进入了副歌，彭羚特别的嗓音，像雨后天晴似的照亮了我。彼时我并不知道这首歌的名字，只知道歌词里有“仁爱路”三个字，我也不知道是香港的“仁爱路”，还是台湾的“仁爱路”。歌名很奇怪，但真好听呀。

一年之后，我也住到了苏州的仁爱路旁，我好奇是不是仁爱路就像“人民路”一般，是不是每个城市都有属于自己的“仁爱路”？这个问题一直到现在我也没有得到答案。我仅仅向自己抛出了问题。恩，我是个喜欢给自己问题，但又不去寻求答案的人。

十二年后，我上周去听了杨丞琳的演唱会，这是我有一些特别记忆的女歌手。以前发生了一些和她相关的事情，被我放在记忆里私藏。而这记忆，已经是快二十年以前的了。记忆是很奇怪的东西，有些记忆会随着时间推移慢慢被遗忘，有些记忆却会随着记忆越来越在脑子里清晰。我还记得那年隔壁班的女生唱着《一千零一个愿望》在我旁边款款走来的景象，我不能说很漂亮，我只想说真美好。

有时候会觉得二十年浑浑噩噩，幸运的是，自己的心智自觉有慢慢地在打开。当然，也许几年之后，我反观此时的我，又会有很多地不同。但总之还是有一些进步的。人生之路，道阻且长，一步一步走吧！
* Footnotes

[fn:1] https://wiki.mbalib.com/wiki/%E7%9B%AE%E7%9A%84%E9%99%90%E5%88%B6%E5%8E%9F%E5%88%99
