#+title: A Bite Of Cybersecurity
#+OPTIONS: author:"Luo Jie" ^:{}
#+startup: content
#+HUGO_BASE_DIR: ./../
#+HUGO_SECTION: posts
#+HUGO_CUSTOM_FRONT_MATTER: :toc true :isCJKLanguage true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2023-05-06]
#+HUGO_TAGS:
#+HUGO_CATEGORIES:
#+hugo_weight: auto
#+hugo_auto_set_lastmod: t
#+startup: noindent
* Terms :@terms:

All posts in here will have the category set to /terms/.
** 工行融 e 行个人信息保护政策分析 :org:hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: PII-Analysis-for-ICBC
:EXPORT_AUTHOR: 丛朝
:EXPORT_DATE: [2023-05-29 Sun]
:END:

#+begin_quote
本文尝试对工行融 e 行的个人信息保护政策做出一些分析，我尝试通过这些分析得出一些关键字。以作为其他分析时的参考。
#+end_quote

*** 基于功能的数据和基于数据的功能
从信息安全三位一体的角度上说，我们需要保护的一是服务，二是数据，即 Service & Data。在做个人信息识别，和资产识别时，可以分别从基于功能的数据和基于数据的功能的角度来展开。

打比方，在穷举一个产品具有的所有功能的同时，我们可以将每一个功能用到的数据，特别是个人信息相关的数据整理出来。如此，在产品功能逻辑上，就可以达到全部的覆盖。

从我个人的角度，“基于功能的数据”恐怕是更为适合我自己去识别个人信息以及资产的方式。

那如何理解“基于数据的功能”呢？在一个系统的运行环境中，个人（actor）这是比较容易识别的，而有关个人的数据，在每个评估者那儿都应该有其积累的经验值。根据这个经验值，评估者在运行环境中，可去结合已有的功能分析，更进一步，可以去评估将来可能会有的功能场景。

从实践的角度来看，我认为评估者应当先对系统运行环境进行全方位分析，基于分析结果，评估个人信息及资产。然后再用自己的经验值作为验证。
所以说，基于功能的数据和基于数据的功能，两者在行程安全概念的过程中，相辅相成，缺一不可。

*** 工行融 e 行关键字识别
为了找出这些关键字，我对原文中加粗的字体，做了解析。同时也尝试做了一个词云。执行的代码如下：
#+begin_src python :session :results file
import sys
import matplotlib
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from wordcloud import STOPWORDS
from requests_html import HTMLSession

# get links
session = HTMLSession()
url = 'https://m.icbc.com.cn/ICBC/disclaimer/2.htm'
r = session.get(url)

# select the selector
sel = '#infoDetailPage > div.infoText.fs16 > p > strong'
bold_text = r.html.find(sel)

def get_text_from_sel(sel):
    mylist = []
    try:
        results = sel
        for result in results:
            mytext = result.text
            mylist.append(mytext)
        return mylist
    except:
        return None

bold_text_string = ' '.join(get_text_from_sel(bold_text))

# set STOPWORDS
sw = set(STOPWORDS)
sw.add("一")
sw.add("二")
sw.add("三")

wordcloud = WordCloud(scale=4,
                      background_color='white',
                      stopwords=sw,
                      font_path='/usr/share/fonts/OTF/NotoSansCJKsc-Regular.otf').generate(bold_text_string)

# plt, fontset, imshow, etc
from matplotlib import font_manager
font_dirs = '/home/lj/Downloads/transfonter.org-unpack-20230527-152629'
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)

# %matplotlib inline
plt.figure(dpi=300, figsize=(24,8))
matplotlib.rcParams['font.family'] = 'WenQuanYi Zen Hei'
plt.title(label='常见水果热力图')
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
# plt.show()
fname = '/home/lj/Pictures/icbc_pii_bold_text.png'
plt.savefig(fname)
fname
#+end_src

** 工行融 e 行个人信息保护政策 :org:hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: A-PII-Example-from-ICBC
:EXPORT_AUTHOR: 丛朝
:EXPORT_DATE:
:END:
[2023-05-15 Mon 12:15]

#+begin_quote
本文对原文做了个别修改，如需参考原文，见：https://m.icbc.com.cn/ICBC/disclaimer/2.htm
#+end_quote
我是工商银行的用户，前几天在使用该银行服务的时候，在手机端被提示了工商银行最新的个人信息保护政策。记录以下要点。

 * 问：工行融 e 行将对个人信息做哪些处理？ :: 收集、使用、存储、提供、转让、公开和删除


数据使用实体需要向数据被收集个体（简称“个体”）阐述相关事宜，见下：
 * 数据使用实体将说明个体信息类型及其用途，以便数据个体了解针对某一特定功能收集个人信息的目的、方式、范围及可能的后果等。
 * 当个体使用某些功能时，数据使用实体需获得个体的明示同意后，可收集个体的某些敏感个人信息，例如个体的 *通讯录*, *生物识别信息* 等，拒绝提供这些信息会影响个体正常使用相关功能。
 * 数据使用实体不应主动提供或转让个体的个人信息与第三方，如存在其他提供或转让个体个人信息情形，数据使用实体需征得个体的明示同意。


  * 问：什么是明示同意？ :: explicit consent 明示同意是指个体通过书面、口头等方式主动作出纸质或电子形式的声明，或者自主作出肯定性动作，对个体的个人信息进行特定处理作出明确授权的行为。
  * 问：肯定性动作包括哪些？ :: 肯定性动作包括个体的主动勾选、主动点击“确定”“同意”“注册”“发送”“拨打”、主动填写或提供等。

*** 保护个人信息的几个原则
    [2023-05-17 Wed 10:46]

数据使用实体需要深知个人信息对个体的重要性，需尽力保护个体的个人信息安全。同时，数据使用实体需要恪守以下 7 个原则以保护个体的个人信息：
 * 权责一致原则 :: 指在一个组织中的管理者所拥有的权力应当与所承担的责任相适应的准则。The principle of consistency of rights and responsibilities
 * 目的明确原则 :: 具有合法、正当、必要、明确的个人信息处理目的。
 * 选择同意原则 :: 指向个人信息主体明示个人信息处理目的、方式、范围、规则等，征求其授权同意。换言之，选择同意原则即是要求企业尊重用户的事先同意权，征求同意的行为需发生在未对用户个人信息采取任何措施之前，例如在注册 App 前需勾选同意用户协议等。
 * 最小必要原则 :: Minimum and necessary
 * 确保安全原则 :: 具备与所面临的安全风险相匹配的安全能力、并采取足够的管理措施和技术手段，保护个人信息的保密性、完整性、可用性。
 * 主体参与原则 :: 指向个人信息主体提供能够访问、更正、删除其个人信息，以及撤回同意、注销账户等方法。主体参与原则赋予用户的是事后监督权，保护的是用户事后的反悔权，或者是用户不同意的自由。根据实践，相较于选择同意权，企业更容易忽视用户的主体参与权利。
 * 公开透明原则 :: 以明确、易懂和合理的方式公开处理个人信息的范围、目的、规则等，并接受外部监督


**** 从目的明确原则展开的目的限制原则 (the principle of purpose limitation)[fn:1]
[2023-05-17 Wed 11:26]

目的限制原则 (the principle of purpose limitation), 也称目的拘束原则，是个人信息保护法中最基本的一项原则，贯穿于个人信息处理活动的全过程，无论处理者是谁，也不管属于何种类型的处理活动，都必须受到该原则的拘束。目的限制原则是个人信息保护的基石，在个人信息保护法中具有重要的地位，该原则也被称为个人信息保护法的“帝王条款”。

个人信息保护法第六条规定：
#+begin_quote
处理个人信息应当具有明确、合理的目的，并应当与处理目的直接相关，采取对个人权益影响最小的方式。收集个人信息，应当限于实现处理目的的最小范围，不得过度收集个人信息。
#+end_quote

**** 个人信息，敏感个人信息的定义
[2023-05-17 Wed 12:59]

个人信息是以电子或者其他方式记录的与已识别或者可识别的自然人有关的各种信息，不包括匿名化处理后的信息。
敏感个人信息是一旦泄露或者非法使用，容易导致自然人的个人尊严受到侵害或者人身、财产安全受到危害的个人信息，包括生物识别、宗教信仰、特定身份、医疗健康、金融账户、行踪轨迹等信息，以及不满十四周岁未成年人的个人信息。

*** 工商银行相关的技术细节，索引
[2023-05-22 Mon 12:44]
 * 如何收集和使用个人信息
 * 如何使用 Cookie 技术
 * 如何存储和保护个人信息
 * 如何提供，转让和公开披露个人信息
 * 个体如何管理自身的个人信息
 * 如何处理未成年人信息
 * 政策如何更新
 * 如何联系个人数据使用实体


**** 如何收集和使用个人信息

应用会收集在使用服务过程中主动输入或因使用服务而产生的信息。依据法律法规及监管要求，个体需提供或授权数据使用实体收集必要的个人信息。如果个体拒绝提供，其将无法使用相应功能或服务。

在注册时，按照使用本行、他行发行卡注册的途径，收集的信息略有区别。当使用本行卡注册时，需要：
 * 手机号码
 * 身份证信息
 * 银行卡号
 * =验证银行卡密码=


若使用的是他行发行卡，则需要：
 * 他行卡号
 * 姓名
 * 性别
 * 手机号码
 * 证件类型
 * 证件号码
 * 证件有效期
 * 联络地址
 * 职业
 * 国籍，
同时，将以下信息发送至中国银联或人民银行进行信息查询与核验，以完成注册：
 * 姓名
 * 证件类型
 * 证件号码
 * 他行卡号


当注册服务时，数据使用实体会采集个体的人脸信息进行身份认证，可能会将人脸信息发送至公安部进行核验并接受验证结果。如果拒绝采集人脸信息，将无法注册该服务。

当使用数据使用实体提供的服务时，个体可能需要向实体提供或授权实体收集相应服务所需的个人信息。如果个体拒绝提供，个人将无法使用相应功能或服务。
 * 当登录时，银行将对登录手机号码、登录密码或手势密码进行有效性核验，首次登录时将验证银行卡取款密码和短信验证码，必要时会验证人脸信息。如个体忘记登录密码需要重置时，银行将根据个体所选择场景的需要验证个体的身份信息，包括手机号码、姓名、证件类型、证件号码、银行卡号、银行卡取款密码、人脸信息。银行还会收集设备信息用语硬件绑定和登录安全加固。如个体不提供以上信息，个体将无法登录或者找回密码，但这不影响个体正常使用未登录情况下可用的功能或服务。
 * 为了让个体更安全、便捷地使用登录服务，如果个体的设备与银行应用的移动版本均支持指纹/面容 ID 功能，个体可以选择通过指纹 / 面容 ID 功能登录银行应用移动端。个体需在其设备上录入个体的指纹 / 面容信息，在个体进行指纹 / 面容 ID 登录移动端时，个体需在其设备上完成指纹 / 面容 ID 验证。银行仅接收验证结果，并不收集个体的指纹 / 面容信息，其信息仅在个体授权采集指纹 / 面容信息的设备上保存和处理。如个人不想使用指纹 / 面容 ID 登录，仍可通过其他方式进行登录。个体可意通过移动端开启或关闭指纹 / 面容 ID 登录功能。
 * 为了让个体更安全、便捷地使用登录服务，如移动端支持声纹登录功能，个体可选择通过声纹登录移动端，银行会采集个体的声纹信息，在经过个体的明示同意和身份认证后，个体的声纹信息将被加密存储于银行信息系统后台数据库中。如个体拒绝授权银行采集个体的声纹信息，银行将无法提供声纹登录服务。个体仍可以通过其他方式登录。个体可以通过移动端开启或关闭声纹登录功能。
 * 当个体在注册、登录、注销电子银行，或在功能开通、查询、变更等交易需核实身份或辅助认证场景时，出于维护个体的信息、账户、资金安全及风险控制等原因，或法律法规、监管规定要求必须开展客户身份核实的场景时，银行会要求个体通过人脸识别进行身份核验。如果个体是未成年人，需要由其监护人通过人脸识别完成验证。
   在人脸识别时，银行会采集个体的人脸信息，通过活体检测和人脸比对等技术，核验个体的真实身份，银行会使用个体在电子银行、自助终端、网点柜面等渠道授权留存的人脸信息，或通过有权机关（包括但不限于中国人民银行、公安部及其授权机构）查询及使用您的身份信息及人脸照片信息。在必要时，银行会将个体的人脸信息发送至上述机构进行核验并接收验证结果。人脸识别验证后，个体的人脸信息将被归档存储于银行系统，以作为交易留证资料。如果个体不提供人脸信息进行采集验证，银行将无法为个体提供根据业务性质及其风险控制等原因必须进行人脸识别验证的产品或服务。
   个体可以授权银行将个体的人脸信息保存至银行信息库，可实现 7*24 小时人脸识别认证服务。经过个体的明示同意和身份认证后，个体的人脸信息将被加密存储于银行人脸识别信息库。个体可意登录银行移动端，开通、终止人脸识别服务或更新个体的人脸信息。
 * 为了让个体更安全、便捷地使用转账、支付服务，如个体的设备与移动端版本均支持指纹、面容功能，对于某些品牌或型号的设备，个体可选择开通指纹、刷脸支付功能。个体需要在设备上录入个体的指纹、面容信息，在个体进行指纹，刷脸支付时，个体需要在其设备上完成指纹，面容验证。银行仅接收验证结果，并不收集个体的指纹，面容信息，其信息仅在个体授权采集指纹，面容信息的设备上保存和处理。如个体不想使用指纹，刷脸支付，仍可通过其他方式进行转账，支付。个体可以通过应用开启或关闭指纹，刷脸支付功能。
 * 当个体通过第三方授权登录应用时，银行可能从第三方（如微信，支付宝，Apple）收集个体授权提供的账户信息（头像，昵称，地区，性别），并在个体同意本政策后将个体的第三方账户与其银行账户绑定，使个体可以通过第三方账户直接登录并使用银行的产品或服务。个体可以通过应用开启或关闭上述第三方授权登录功能，并可以查询第三方账户绑定历史。
 * 当个体使用银行提供的实名认证服务时，银行将根据个体所根据场景的需要验证个体的姓名、证件类型（身份证，护照，军官证，士兵证，港澳台居民来往通行证，临时身份证，户口本，警官证，外国人永久居留证，边民出入境通行证），证件号码，银行卡号账号，短信验证码，人脸信息，并可能通过验证账号，卡密码方式对有关信息进行有效性核验。如个体不提供上述信息，银行将无法向个体提供需完成实名认证后方可使用的产品或服务，但这不影响个体正常使用银行的其他功能。
 * ……
 * ……
 * ……
 * 在以下情形中，个体选择是否授权个人信息使用实体收集，使用个体的个人信息：
   * 基于相机（摄像头）的功能 :: 个体可使用扫码支付，二维码识别，银行卡识别，身份证识别，人脸识别，同屏解说，远程视频审核等服务。
   * 基于相册（图片库）的功能 :: 个体可使用头像上传，电子回单保存，二维码识别，银行卡及身份证识别等服务。
   * 基于地理位置的功能 :: 个体可开启定位服务，用于网络金融交易风控，提高查询附近网点，获得优惠商户信息的准确性。
   * 基于麦克风的功能 :: 个体可使用音频 U 盾，声纹识别，语音搜索，语音转账，语音唤醒，同屏解说，远程视频审核等服务。
   * 基于蓝牙的功能 :: 个体可使用蓝牙 U 盾等服务。
   * Face ID :: 个体可使用登录，支付等服务。
   * 基于存储的功能 :: 用语手机银行登录，我的客服，扫一扫，登录图像图片保存，同屏解说等功能或服务，提供客户端升级相关信息。
   * 基于电话的功能 :: 用于读取手机设备 ID 等基础信息，并标识设备绑定信息以保障客户在登录，支付时的交易安全。当个体使用忘记密码，账户挂失或解挂等功能的音视频审核服务和同屏解说服务时，需要确认电话状态，避免在通话过程中进入音视频通讯而出现设备占用等异常状态。
   * 基于 NFC 的功能 :: 个体可使用云闪付，工银芯管家等服务。
   * 基于通讯录的功能 :: 个体可使用手机号转账，话费充值，汇款短信通知等服务。
   * 基于指纹的功能 :: 个体可使用指纹登录，指纹登录设置等服务。
   * 基于剪切板的功能 :: 个体可使用云口令识别，转账快捷跳转功能，银行系统后台不保存个体的剪切板内容。
   * 基于投屏录屏的功能 :: 个体可使用同屏解说服务。
   * 基于应用内下载安装 App 的功能 :: 个体可使用检测到新版本后的客户端升级服务。
   * 基于悬浮窗的功能 :: 个体可参加任务中心活动，使用音视频审核服务和同屏解说服务。
   * 基于加速度传感器的功能 :: 个体可使用翻转退出登录和摇一摇服务。
     上述功能可能需要个体在其设备中向银行开启个体的相机（摄像头），相册（图片库），地理位置（位置信息），麦克风，蓝牙，Face ID，存储空间，电话，NFC，通讯录，指纹，剪切板，投屏录屏，应用内下载安装 App，悬浮窗的访问权限，以实现这些功能所涉及的信息的收集和使用。

** What is Back Office? :hugo:org:
:PROPERTIES:
:EXPORT_FILE_NAME: What-is-Back-Office
:EXPORT_DATE:
:END:

*** Definition
#+begin_quote
The back office is a counter concept against front office.
#+end_quote

** What is Information Security Management :hugo:org:
:PROPERTIES:
:EXPORT_FILE_NAME: What-is-Information-Security-Management
:EXPORT_DATE: [2023-05-14 Sun]
:END:

#+begin_quote
Information security management validates that appropriate policies, procedures, standards, and guidelines are implemented to ensure business operations are conducted within an acceptable level of risk.
#+end_quote


* Emacs :@emacs:
** doomemacs GUI 中文显示及输入法设置 :hugo:emacs:org:
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_FILE_NAME: doomemacs GUI 中文显示设置
:EXPORT_DATE: [2023-10-03 Mon]
:END:
本文尝试对 doomemacs 的中文字体显示及输入法设置，做一个记录。先说我的配置：
 * 中文显示字体，[[https://github.com/be5invis/Sarasa-Gothic][Sarasa Gothic SC]]
 * 中文输入法，[[https://github.com/tumashu/pyim][PYIM]] + [[https://github.com/merrickluo/liberime][liberime]]
 * 输入法方案，[[https://www.fkxxyz.com/d/cloverpinyin/][四叶草]]
 * 其他…

*** doomemacs GUI frame 中文显示
我一般只会使用窗口模式下的 emacs，此前在使用我自身做的 emacs 配置时，发现配置中文只要简单地设置 CJK 字符就可以，但到了用 doomemacs 时，我尝试了各种方法，总是不行。[[https://emacs-china.org/t/doom-emacs/23513/10][最终发现了一个 hook 的使用]]，如下：
#+begin_src emacs-lisp
(defun +set-cjk()
  "set cjk for Emacs"
  (interactive)
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font)
                      charset
                      (font-spec :family "Sarasa Gothic SC"))))

(add-hook 'after-setting-font-hook #'+set-cjk)
#+end_src
即在 doomemacs 设置完字体以后，我们再来覆盖 CJK 的字体。

*** 中文输入法，PYIM 和 liberime
在 emacs 下，PYIM, emacs-rime, [[https://github.com/laishulu/emacs-smart-input-source][SIS]]，我都用过，我在这里不赘述几种输入法的优劣。单从我个 人的使用习惯来说，我更喜欢 PYIM + liberime 的组合，就像 PYIM 作者说的那样，PYIM 就像我的朋友一样，一直陪伴的着我，而我唯一觉得用得不舒服的地方，在于 PYIM 自带字库，以及云输入法，我总觉得会有些延迟。

基于以上的考虑，最终我想用 PYIM 作为前端，rime 输入法引擎作为后端。至少试下来，整体的效果还是很好的。

*** Rime 输入法方案——四叶草
我喜欢这个输入法方案。我的个人电脑上，安装的是 Arco Linux, 有些字体的支持，emoji 的支持有限，这里着重说下几个问题。

**** 问题一，输入法 emoji 不显示
安装 fontconfig 的配置，见 https://github.com/szclsya/dotfiles/blob/master/fontconfig/fonts.conf

**** 问题二，四叶草输入方案
最好不要和系统输入法共用一个。

** =before-save-hook= 默认不是 =buffer local variable= :org:emacs:hugo:
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_DATE: [2024-01-15]
:EXPORT_FILE_NAME: Emacs before-save-hook 不是 local variable
:END:
我最近准备用 [[https://docutils.sourceforge.io/rst.html][reStructuredText]] 做结构化文档的处理。
基于我已经是一个重度的 =org-mode= 患者，我在做任何笔记的时候，离开 =org-mode= 便显得各种
不适应。虽然能看到 [[https://daringfireball.net/projects/markdown/][Markdown]] 很清秀，reStructuredText 很 sexy，但我大有“野花不如家花香”的
感慨。

每当我吸完其他的工具之后，最后还是乖乖回到了 =org-mode=. 但我不得不承认的是， reStructuredText 配合 [[https://www.sphinx-doc.org/en/master/][Sphinx]] 有一种化繁为简的美感。我曾经有过想用 =org-mode= 在大型
项目里实践 [[https://en.wikipedia.org/wiki/Literate_programming][Literate programming]] 的想法，但一想到要如何推广 =org-mode=,整件事情到那儿就
戛然而止了。毕竟推广 =org-mode= 和推广 =GNU Emacs= 一样艰难，人各有喜好，各有接受程度，
=org-mode= 和 =GNU Emacs= 更像是现代武林的邪派武功。

言归正传，我用 =org-mode= 记录了一篇笔记之后，使用 [[https://github.com/msnoigrs/ox-rst][ox-rst]] 导出到 rst 格式。这里遇到一个问题：
我不想每次保存完 =org-mode= buffer 之后，在手动去做一些导出，那样显得我太蠢了，无法体现出
=GNU Emacs= 的邪典艺术。所以做一个自动导出的设置吧， *Let's trial and error!!!*

*** Trial 1 - =after-save-hook=
我先想到的是用 =hook=, 一通 =C-h v= 操作下来，试下 =after-save-hook=,代码很简单：
#+caption: example for bad setting with after-save-hook
#+begin_src emacs-lisp
(add-to-hook 'after-save-hook #'org-rst-export-to-rst)
#+end_src

我很悲剧的发现，加了这个 hook 之后，我没有办法保存文件。似乎每次执行导出的操作后，buffer 就变成
编辑过后的状态，我神奇地搞了一个死循环。一直 =save-export-save-export...=.

*** Trial 2 - =before-save-hook=
既然 =save-buffer= 之后不行，那么就在保存之前吧，毕竟这样很合理。
#+caption: example for bad setting with before-save-hook
#+begin_src emacs-lisp
(add-hook 'before-save-hook #'org-rst-export-to-rst)
#+end_src

OK, 保存的问题解决了。但悲剧总是从一种形式转变成另外一种形式，我以为 =before-save-hook= 是 =local variable=, 但他不是的。我保存的每一个文件，都来了一个 =.rst= 后缀，你能想象 =foo-bar.rst.rst= 的美吗？

*** Tiral 3 - =before-save-hook= localization
那…… 有没有一种办法，创造一个 =local variable= 呢？

有的。在[[https://stackoverflow.com/questions/1931784/emacs-is-before-save-hook-a-local-variable][这里]]我找到了答案。这个答案已经在万维网中存在了 14 年，在今天终于被我捕获了。
进而我看了 =add-hook= 的 manual, 它的 signature 是这样的：
#+caption: example for good setting with before-save-hook
#+begin_src emacs-lisp
(add-hook HOOK FUNCTION &optional DEPTH LOCAL)
#+end_src

就是这个 =LOCAL=, 将它设置成 =t= 之后，会创建一个 =before-save-hook= 的同名 =local variable=. 而这个 hook 的执行顺序，则是先按照 =global variable= 的变量执行一次，
在执行一次 =local variable=.

于是乎，这个问题解决了。额，你说问题是什么？那就是我可以保存完 =org-mode= 的文件后，自动得到
=*.rst= 的文件了。 *Bravo!*

*** 更多设置
在这里其实还涉及到我对某个 =org-mode buffer= 做的 =local variable= 的设置，举个例子吧：
#+caption: example for local variable setup
#+begin_example
=# Local Variables:=
=# eval: (add-hook 'before-save-hook #'org-rst-export-to-rst nil t)=
=# End:=
#+end_example

当然，还得加上导出文件的设置，比如：
#+caption: export file setting
#+begin_quote
=#+export_file_name: /you/export/file/path=
#+end_quote

OK, 打完，收功！


* 碎碎念 :@只言片语:
** 一枝花 :lifestyle:
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_FILE_NAME: 一枝花
:EXPORT_DATE: [2023-11-21]
:END:
我犹豫了很久，要不要在这个 blog 里写一些稍微偏私人的东西。考虑的点不外乎那么几点，一方面我想找个地方，一个能被人看到，听到的地方说些什么，另一方面，我又不想让知道我有这么一面。我通过一段时间的观察，似乎我周围，没什么人还保留着看 blog 的习惯。

所以我还是在这里写写吧。写什么都好，谁来看都行，我只管写我的。

“一枝花”是彭羚一张专辑的名字，我下班之后从坐班车起，到打开家门。差不多可以将这张专辑从头到尾听两遍。我最早听彭羚的歌，是在十二年前一次晚间下班，那时加班班车，司机师傅喜欢放一个音乐电台，歌曲以怀旧为主。我听了王杰，张清芳，齐秦这些人的歌，张清芳也是很特别的歌手，我听了她的《加州阳光》，《大雨的夜里》，《对话练习》等等，也陪我度过了很多孤独的时光。但这次下班是特别的，我打着瞌睡，电台里放的是彭羚的《给我一段仁爱路》，这首歌前奏乍听很聒噪，歌词也很无脑。等到进入了副歌，彭羚特别的嗓音，像雨后天晴似的照亮了我。彼时我并不知道这首歌的名字，只知道歌词里有“仁爱路”三个字，我也不知道是香港的“仁爱路”，还是台湾的“仁爱路”。歌名很奇怪，但真好听呀。

一年之后，我也住到了苏州的仁爱路旁，我好奇是不是仁爱路就像“人民路”一般，是不是每个城市都有属于自己的“仁爱路”？这个问题一直到现在我也没有得到答案。我仅仅向自己抛出了问题。恩，我是个喜欢给自己问题，但又不去寻求答案的人。

十二年后，我上周去听了杨丞琳的演唱会，这是我有一些特别记忆的女歌手。以前发生了一些和她相关的事情，被我放在记忆里私藏。而这记忆，已经是快二十年以前的了。记忆是很奇怪的东西，有些记忆会随着时间推移慢慢被遗忘，有些记忆却会随着记忆越来越在脑子里清晰。我还记得那年隔壁班的女生唱着《一千零一个愿望》在我旁边款款走来的景象，我不能说很漂亮，我只想说真美好。

有时候会觉得二十年浑浑噩噩，幸运的是，自己的心智自觉有慢慢地在打开。当然，也许几年之后，我反观此时的我，又会有很多地不同。但总之还是有一些进步的。人生之路，道阻且长，一步一步走吧！
** 谈谈中文技术名词的翻译 :cliche:
:PROPERTIES:
:EXPORT_AUTHOR: 丛朝
:EXPORT_FILE_NAME: 谈谈中文技术名词的翻译之 ssh 爆破
:EXPORT_DATE: [2024-01-10]
:END:
我在以往工作中接触过所谓 ssh ”爆破“这两个字，彼时因为不需要具体使用这个术语，总觉得“爆破”两个字好屌。当时会想，到底什么牛的技术才可以当得起“爆破”两个字。
是不是一个命令一输入，突然 ssh 协议站就山崩地裂，崩溃以至于无法工作，再者无法回复，最终只能向黑客妥协，交出自己 ssh 所有的控制权。

“砰！”

直到今天，我才发现，“爆破”等于“暴力破解”，实乃“暴破”，英文所谓 "brute force attack" 也。

在搞清楚这个问题后，我不由汗颜。也意识到，原来看起来高大上的一些概念，很大程度上是因为中文翻译导致的以讹传讹。甚至于我在搜索引擎中搜索“暴破”两个字，几乎没有匹配到内容。

语言创造出来，本是为了理性交流，让概念通用化，但英文的原意经由中文的转义后，暴力破解的重复性，变成了爆炸破坏的瞬时性。这可以说造成了某种南辕北辙的效果。

传说当年最早翻译福尔摩斯的是一位福建人，老兄将 Holmes 中的 H 发成了 F。翻译人名的时候，可能无伤大雅，但翻译技术名字，要是也如此，那对于技术的传播，反而筑起了一道理解的壁垒。
记录下这件事情，权当给自己勉励吧。要想在技术上有所建树，切记要中西合璧，如此才相得益彰。

* Footnotes

[fn:1] https://wiki.mbalib.com/wiki/%E7%9B%AE%E7%9A%84%E9%99%90%E5%88%B6%E5%8E%9F%E5%88%99
